<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.9">
  <POU Name="PRG_TEST" Id="{b6e50351-783e-4948-93d8-763e2dd52247}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM PRG_TEST
VAR
	fbFLOOR_Test : FLOOR_Test;
	fbMAV_DW_Test : FILTER_MAV_DW_Test; 
	//fbMAV_W_Test : FILTER_MAV_W_Test; 
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[TcUnit.RUN();]]></ST>
    </Implementation>
    <LineIds Name="PRG_TEST">
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>